apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80 # Service'in dışında kullanılacak port
      targetPort: 3000 # Deployment içindeki container'ın kullanmış olduğu port
